name: Create OCM Release Branch

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: 'Branch to cut to (format: releases/vMAJOR.MINOR, e.g., releases/v0.1 or releases/v1.1)'
        required: true
      source_branch:
        description: 'Branch to cut from (default main)'
        required: false
        default: 'main'

jobs:
  create-release-branch:
    environment:
      name: ocm-release
    name: Create Release Branch from ${{ github.event.inputs.source_branch }} to ${{ github.event.inputs.target_branch }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - name: Generate App Token
        id: get_token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        continue-on-error: true
        with:
          app-id: ${{ secrets.OCMBOT_APP_ID }}
          private-key: ${{ secrets.OCMBOT_PRIV_KEY }}
          permission-contents: write

      - name: Validate and create release branch
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8
        env:
          TARGET_BRANCH: ${{ github.event.inputs.target_branch }}
          SOURCE_BRANCH: ${{ github.event.inputs.source_branch }}
        with:
          github-token: ${{ steps.get_token.outputs.token || secrets.GITHUB_TOKEN }}
          script: |
            const createReleaseBranch = await import('${{ github.workspace }}/.github/scripts/validate-next-release-branch.js');
            await createReleaseBranch.default({ github, context, core });
